# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5357e9c9c87f097af0fdad42853692c10fe777dbf20c4b68168e7fa97f961c41ff2228fe6b5d2d0ffea3a34d4734760e436233ff5aa8f418223112070464c34f

test:
  secret_key_base: 19f54a8ae9c8178d32fe129676c935d9562d009e34c78bacc7cc6426f473f6dc3734bcc363e61e1cd4fc06d2f0ced1393d0bada20c75755c5a4ead22c7ce3270

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
